<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SubMatcher</AssemblyName>
    <PublishAot>true</PublishAot>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets/icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.22" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.22" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.13" />
    <PackageReference Include="Semi.Avalonia" Version="11.3.22" />
    <PackageReference Include="Semi.Avalonia.DataGrid" Version="11.3.13" />
    <PackageReference Include="Irihi.Ursa" Version="1.15.1" />
    <PackageReference Include="Irihi.Ursa.Themes.Semi" Version="1.15.1" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets/icon.ico" />
    <AvaloniaResource Include="Assets/icon.png" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SubMatcher.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SubMatcher.Core\SubMatcher.Core.csproj" />
  </ItemGroup>

</Project>
